version: '3.8'

services:

    redis-master:
        image: redis:alpine
        hostname: redis
        container_name: redis-master
        ports:
            - "6379:6379"
        networks:
            - demo
        command: [ "redis-server", "--appendonly", "yes" ]

    redis-slave:
        image: redis:alpine
        container_name: redis-slave
        ports:
            - "6380:6379"
        depends_on:
            - redis-master
        networks:
            - demo
        command: [ "redis-server", "--slaveof", "redis-master", "6379" ]

    demo-service:
        image: anatolydudko/spring-boot-with-redis-in-action:0.0.2
        hostname: demo-service
        container_name: demo-service
        ports:
            - "8080:8080"
        environment:
            - "SPRING_DATA_REDIS_HOST=redis-master"
        depends_on:
            - redis-master
        networks:
            - demo

networks:
    demo:
        driver: bridge
