version: '3.8'

services:

    redis-master:
        image: redis:alpine
        hostname: redis
        container_name: redis-master
        ports:
            - "6379:6379"
        command: [ "redis-server", "--appendonly", "yes" ]
        networks:
            - ${GLOBAL_NETWORK:-service}

    redis-slave:
        image: redis:alpine
        container_name: redis-slave
        ports:
            - "6380:6379"
        depends_on:
            - redis-master
        networks:
            - ${GLOBAL_NETWORK:-service}
        command: [ "redis-server", "--slaveof", "redis-master", "6379" ]

    spring-boot-redis:
        image: anatolydudko/spring-boot-with-redis-in-action:3.4.3
        hostname: spring-boot-redis
        container_name: spring-boot-redis
        ports:
            - "8080:8080"
        environment:
            - "SPRING_DATA_REDIS_HOST=redis-master"
        depends_on:
            redis-master:
                condition: service_started
        networks:
            - ${GLOBAL_NETWORK:-service}

networks:
    service:
        driver: bridge
