server:
    port: 8080

logging:
    level:
        root: INFO

spring:
    application:
        name: spring-boot-with-redis-in-action
    data:
        redis:
            host: localhost
            port: 6379

management:
    server:
        port: 8282
    endpoints:
        web:
            base-path: /mng
            exposure:
                include: '*'
    endpoint:
        health:
            show-details: always

redis:
    keys:
        item:
            timeToLive: PT10M
